modLoader="javafml"
loaderVersion="[32,)"
license="https://github.com/minecraftabnormals/Bamboo-Blocks/blob/master/LICENSE.txt"
issueTrackerURL="https://github.com/minecraftabnormals/Bamboo-Blocks/issues"

[[mods]]
    logoFile="logo.png"
    modId="bamboo_blocks"
    version="${file.jarVersion}"
    authors="bageldotjpg & Endergized"
    credits="Pugz & Farcr"
    displayName="Bamboo Blocks"
    description='''Fun Bamboo Blocks to build with!'''


[[dependencies.bamboo_blocks]]
    modId="forge"
    mandatory=true
    versionRange="[32.0.72,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.bamboo_blocks]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.1]"
    ordering="NONE"
    side="BOTH"

[[dependencies.bamboo_blocks]]
    modId="abnormals_core"
    mandatory=true
    versionRange="[2.0.1,)"
    ordering="AFTER"
    side="BOTH"
