modLoader="javafml"
loaderVersion="[31,]"
logoFile="logo.png"
authors="Pugz & bageldotjpg"
credits="*Endergized*"

[[mods]]
    modId="bambooblocks"
    version="${file.jarVersion}"
    displayName="Bamboo Blocks"
    description='''
    Fun Bamboo Blocks to build with!'''

[[dependencies.bambooblocks]]
    modId="forge"
    mandatory=true
    versionRange="[31.1.46,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.bambooblocks]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"

[[dependencies.bambooblocks]]
    modId="abnormals_core"
    mandatory=true
    versionRange="[1.0.6,)"
    ordering="AFTER"
    side="BOTH"
